apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-clone-deployment
spec:
  selector:
    matchLabels:
      app: reddit-clone
  template:
    metadata:
      labels:
        app: reddit-clone
    spec:
      imagePullSecrets:
        - name: artifact-registry-secret
      containers:
        - name: reddit-clone
          image: us-central1-docker.pkg.dev/devopslearning-463313/poc-repo/reddit-clone-app:2
          ports:
            - containerPort: 3000
